config/routes.rb
Rails.application.routes.draw do
  resources :classses
  resources :teachers
  resources :students

  root 'welcome#home'

  get 'page1' => 'welcome#page1'

  get 'page2' => 'welcome#page2'

  get 'home' => 'welcome#home'

end

app/models/classs.rb
class Classs < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classses_controller.rb
class ClasssesController < ApplicationController
  before_action :set_classs, only: [:show, :edit, :update, :destroy]

  # GET /classses
  # GET /classses.json
  def index
    @classses = Classs.all
  end

  # GET /classses/1
  # GET /classses/1.json
  def show
  end

  # GET /classses/new
  def new
    @classs = Classs.new
  end

  # GET /classses/1/edit
  def edit
  end

  # POST /classses
  # POST /classses.json
  def create
    @classs = Classs.new(classs_params)

    respond_to do |format|
      if @classs.save
        format.html { redirect_to @classs, notice: 'Classs was successfully created.' }
        format.json { render :show, status: :created, location: @classs }
      else
        format.html { render :new }
        format.json { render json: @classs.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classses/1
  # PATCH/PUT /classses/1.json
  def update
    respond_to do |format|
      if @classs.update(classs_params)
        format.html { redirect_to @classs, notice: 'Classs was successfully updated.' }
        format.json { render :show, status: :ok, location: @classs }
      else
        format.html { render :edit }
        format.json { render json: @classs.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classses/1
  # DELETE /classses/1.json
  def destroy
    @classs.destroy
    respond_to do |format|
      format.html { redirect_to classses_url, notice: 'Classs was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classs
      @classs = Classs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classs_params
      params.require(:classs).permit(:subject, :credits, :building)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :grade)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :salary, :country)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def page1
  end

  def page2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classses_helper.rb
module ClasssesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/classses/_form.html.erb
<%= form_for(@classs) do |f| %>
  <% if @classs.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classs.errors.count, "error") %> prohibited this classs from being saved:</h2>

      <ul>
      <% @classs.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :credits %><br>
    <%= f.number_field :credits, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :building %><br>
    <%= f.text_field :building, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/classses/edit.html.erb
<h1>Editing Classs</h1>

<%= render 'form' %>

<%= link_to 'Show', @classs %> |
<%= link_to 'Back', classses_path %>

app/views/classses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Listing</h1>

  <div class="row">
    <% @classses.each do |classs| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2>Subject: <%= classs.subject %></h2>
         <h3>Credits: <%= classs.credits %></h3>
         <p>Building: <%= classs.building %></p>
       
         <div class="btn-group">
          <%= link_to 'Show', classs, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_classs_path(classs), class: "btn btn-default" %>
          <%= link_to 'Destroy', classs, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Class', new_classs_path, class: "btn btn-primary" %>

app/views/classses/new.html.erb
<h1>New Classs</h1>

<%= render 'form' %>

<%= link_to 'Back', classses_path %>

app/views/classses/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Subject:</strong>
  <%= @classs.subject %>
</h1>

<h2>
  <strong>Credits:</strong>
  <%= @classs.credits %>
</h2>

<p>
  <strong>Building:</strong>
  <%= @classs.building %>
</p>

<div class="btn-group">
<%= link_to 'Edit', edit_classs_path(@classs), class: "btn btn-default" %> 
<%= link_to 'Back', classses_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
  		<div class="container-fluid">
    	<!-- Brand and toggle get grouped for better mobile display -->
    		<div class="navbar-header">
     			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        			<span class="sr-only">Toggle navigation</span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
      			</button>

      			<%= link_to "CLASSROOM", root_path, class: "navbar-brand" %>

    		</div>

    	<!-- Collect the nav links, forms, and other content for toggling -->
    		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      			<ul class="nav navbar-nav">
      	
        			<li class="active"><%= link_to "Home", root_path %></li>
        			<li><%= link_to "Students", students_path  %></li>  
        			<li><%= link_to "Teachers", teachers_path  %></li>
        			<li><%= link_to "Classes", classses_path  %></li>        
     	    	</ul>
      			<form class="navbar-form navbar-left" role="search">
        			<div class="form-group">
          				<input type="text" class="form-control" placeholder="Search">
        			</div>
        			<button type="submit" class="btn btn-default">Submit</button>
      			</form>
      			<ul class="nav navbar-nav navbar-right">
        			<li><%= link_to "Page1", page1_path %></li>
        			<li><%= link_to "Page2", page2_path %></li>
      			</ul>
    		</div><!-- /.navbar-collapse -->
  		</div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div  class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :age %><br>
    <%= f.number_field :age, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :grade %><br>
    <%= f.number_field :grade, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Listing</h1>

  <div class="row">
    <% @students.each do |student| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= student.name %></h2>
         <h3>Age: <%= student.age %></h3>
         <h3>Grade: <%= student.grade %></h3>
       
         <div class="btn-group">
          <%= link_to 'Show', student, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_student_path(student), class: "btn btn-default" %>
          <%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Student', new_student_path, class: "btn btn-primary" %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Name:</strong>
  <%= @student.name %>
</h1>

<h2>
  <strong>Age:</strong>
  <%= @student.age %>
</h2>

<h2>
  <strong>Age:</strong>
  <%= @student.grade %>
</h2>

<div class="btn-group">
<%= link_to 'Edit', edit_student_path(@student), class: "btn btn-default" %> 
<%= link_to 'Back', students_path, class: "btn btn-default" %>
</div>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :salary %><br>
    <%= f.number_field :salary, class: "form-control"%>
  </div>
  <div class="field form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control"%>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teacher Listing</h1>

  <div class="row">
    <% @teachers.each do |teacher| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= teacher.name %></h2>
         <h3>Salary: $<%= teacher.salary %></h3>
         <p>Country: <%= teacher.country %></p>

       
         <div class="btn-group">
          <%= link_to 'Show', teacher, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_teacher_path(teacher), class: "btn btn-default" %>
          <%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Teacher', new_teacher_path, class: "btn btn-primary" %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Name:</strong>
  <%= @teacher.name %>
</h1>

<h2>
  <strong>Salary:</strong>
  <%= @teacher.salary %>
</h2>

<p>
  <strong>Country:</strong>
  <%= @teacher.country %>
</p>

<div class="btn-group">
<%= link_to 'Edit', edit_teacher_path(@teacher), class: "btn btn-default" %> 
<%= link_to 'Back', teachers_path, class: "btn btn-default" %>
</div>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>

app/views/welcome/page1.html.erb
<h1>Welcome#page1</h1>
<p>Find me in app/views/welcome/page1.html.erb</p>

app/views/welcome/page2.html.erb
<h1>Welcome#page2</h1>
<p>Find me in app/views/welcome/page2.html.erb</p>